services:
  - type: web
    name: opsflow-api
    runtime: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/v1/health
    envVars:
      - key: APP_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:4200
      - key: CORS_ORIGIN_REGEX
        value: https://.*\.vercel\.app
      - key: SEED_DEMO_DATA
        value: true
